apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-container
          image: navin3d/infrasight-auth-service
          ports:
            - containerPort: 8011
          env:
            - name: EUREKA_HOST
              value: eureka-cip
            - name: SERVER_PORT
              value: "8011"
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-cip
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cip
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8011
      targetPort: 8011