apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophet-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prophet-service
  template:
    metadata:
      labels:
        app: prophet-service
    spec:
      containers:
        - name: prophet-conatiner
          image: navin3d/prophet-service
          ports:
            - containerPort: 8013
          env:
            - name: EUREKA_HOST
              value: eureka-cip
            - name: SERVER_PORT
              value: "8013"
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-cip
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: prophet-cip
spec:
  type: ClusterIP
  selector:
    app: prophet-service
  ports:
    - port: 8013
      targetPort: 8013