apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      labels:
        app: server-service
    spec:
      containers:
        - name: server-service-container
          image: navin3d/infrasight-server-service
          ports:
            - containerPort: 8015
          env:
            - name: SERVER_PORT
              value: "8015"
            - name: EUREKA_HOST
              value: eureka-cip
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-cip
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: server-cip
spec:
  type: ClusterIP
  selector:
    app: server-service
  ports:
    - port: 8015
      targetPort: 8015