apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      labels:
        app: server-service
    spec:
      containers:
        - name: server-container
          image: navin3d/infrasight-server-service
          ports:
            - containerPort: 8014
          env:
            - name: EUREKA_HOST
              value: eureka-cip
            - name: SERVER_PORT
              value: "8014"
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-cip
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: server-cip
spec:
  type: ClusterIP
  selector:
    app: server-service
  ports:
    - port: 8014
      targetPort: 8014